### ISSUE TITLE
How can i send a videp to test the perfomance?

### ISSUE THREAD

**Issue by lenka844** [jackyjsy/CVPR21Chal-SLR#10]
very excited about ur code, im trying to test this model in a video to test its performance,but i dont konw how to or where to send the vide in, i have read the issue about the webcamera use, it has to record a video,and process, Does it means i have to process my test video by the same method,such as generate .npy file and generate rawframes and extract skeleton features and so on? Thanks for answering.Appreciate!

**Comment by jackyjsy** [comment]
Yes. You need to process the video into RGB frames or skeleton following the preprocessing guide [data_process/readme.md], and load the provided pretrained model to test it.
