### ISSUE TITLE
Reproduce Results on WLASL dataset

### ISSUE THREAD

**Issue by kdafnis** [jackyjsy/CVPR21Chal-SLR#12]
Thank you very much for providing the code. I would like to reproduce the results on WLASL dataset. Could you please provide me with details about the pre-processing of the data on WLASL dataset?

**Comment by jackyjsy** [comment]
Thanks for reaching out. We are preparing a journal extension for SAM-SLR. The code (including data processing) used for WLASL dataset will be available when we release the preprint version on arxiv. Please check the SAM-SLR-v2 repo [[link]](https://github.com/jackyjsy/SAM-SLR-v2) for updates. We are targeting to release the code and the preprint version in October.
