### ISSUE TITLE
Images' Docker 

### ISSUE THREAD

**Issue by HajarAlnamshan** [jackyjsy/CVPR21Chal-SLR#19]
Hello !

 I facing an issue related to the Nvidia docker image, when I run it by using this command 

`sudo docker run -it --gpus all -v path_to_your_data:/home/smilelab_slr/cvpr2021_allcode/shared_data cvpr2021cha_code /bin/bash`

it gives me this error message: 

```
Unable to find image 'cvpr2021cha_code:latest' locally
docker: Error response from daemon: pull access denied for cvpr2021cha_code, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

```

Any help?

**Comment by jackyjsy** [comment]
Hi Hajar, I've try it myself using the following code:
`sudo docker run -it --gpus all cvpr2021cha_code /bin/bash`
First time it gives me the access denied error, but the second time it works for me. 
Can you try the above command and let me know if your condition persists?

Best,
Songyao

**Comment by HajarAlnamshan** [comment]
It's working in my case
Thank you so much

**Comment by ShashankC10** [comment]
Hey i am getting the same error , will be of great help if i could know how you solved  it.
