### ISSUE TITLE
Wholebody yaml missing 

### ISSUE THREAD

**Issue by iliasprc** [jackyjsy/CVPR21Chal-SLR#2]
Hi, I get the following error when I try to run the demo.py to extract 2d keypoints 

FileNotFoundError: [Errno 2] No such file or directory: 'wholebody_w48_384x288.yaml'

**Comment by jackyjsy** [comment]
Thanks for pointing out. The missing .yaml file is uploaded to the wholepose folder.

**Comment by ErminiaLeonardi** [comment]
I also need the wholebody_w48_384x288.yaml file. Where should I find it?

**Comment by jackyjsy** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'wholebody_w48_384x288.yaml'

It can be found in the Google Drive shared folder [link](https://drive.google.com/drive/folders/1PIsji7VooWsxm2JHdSms57iHB2sCj8PX?usp=sharing)

**Comment by ErminiaLeonardi** [comment]
Hi, a password is required to unzip the validation_labels.zip and test_labels.zip.
How I have to proceed?
Thanks in advance
