### ISSUE TITLE
 CUDA capability is not compatible with the current PyTorch installation

### ISSUE THREAD

**Issue by HajarAlnamshan** [jackyjsy/CVPR21Chal-SLR#20]
Hello
Initially, I would thank the author for this amazing repository

I following step by step of this instruction [[reproduce.md](https://github.com/jackyjsy/CVPR21Chal-SLR/blob/main/reproduce.md)](url)

I'm at  > III: Procedues to reproduce our results > A. For RGB track

and I was struggling with this error since yesterday, it happen when I try to run 
`python main.py --config config/sign/test/test_bone.yaml `

```
UserWarning: 
NVIDIA RTX A5000 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA RTX A5000 GPU with
<img width="970" alt="Screen Shot 1443-08-07 at 12 45 11 PM" src="https://user-images.githubusercontent.com/85832533/157636654-90100cea-ca2d-40e7-ae36-7a243278a6be.png">
 PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
```

Any help? 
Thank you

**Comment by HajarAlnamshan** [comment]
and the it is give me this error 
<img width="1352" alt="Screen Shot 1443-08-07 at 12 56 55 PM" src="https://user-images.githubusercontent.com/85832533/157643082-eb010af9-9f35-45a1-ac83-63da64f8bb35.png">

`FileNotFoundError: [Errno 2] No such file or directory: 'final_models/27_2/bone_epoch_239_9470.pt'`

**Comment by LYF199903** [comment]
You should change the device to 0 in ‘config’ this folder. This is a multi-card parallel program.
