### ISSUE TITLE
Train for bone 

### ISSUE THREAD

**Issue by HajarAlnamshan** [jackyjsy/CVPR21Chal-SLR#21]
Hello!

I run this command for bone's training 
`
python main.py --config config/sign/train/train_bone.yaml`

and it gives me this error

`Traceback (most recent call last):
  File "main.py", line 588, in <module>
    processor = Processor(arg)
  File "main.py", line 215, in __init__
    self.load_data()
  File "main.py", line 224, in load_data
    dataset=Feeder(**self.arg.train_feeder_args),
  File "/home/smilelab_slr/cvpr2021_allcode/GCN/feeders/feeder.py", line 40, in __init__
    self.load_data()
  File "/home/smilelab_slr/cvpr2021_allcode/GCN/feeders/feeder.py", line 59, in load_data
    self.data = np.load(self.data_path, mmap_mode='r')
  File "/home/smilelab_slr/SLR_pytorch/env/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './data/sign/27_2/train_data_bone.npy'`

Any help?
Many thanks 
<img width="1077" alt="Screen Shot 1443-08-14 at 3 52 19 PM" src="https://user-images.githubusercontent.com/85832533/158812428-5ccdefa0-2ea3-40e4-9bde-56dca
<img width="1077" alt="Screen Shot 1443-08-14 at 3 52 19 PM" src="https://user-images.githubusercontent.com/85832533/158812507-f0511278-74a3-4ecd-9328-443e7526ad4c.png">
4f507db.png">

**Comment by JoeNatan30** [comment]
Did you run "python gen_bone_data.py" in "data_gen/"? ([SL-GCN](https://github.com/jackyjsy/CVPR21Chal-SLR/tree/main/SL-GCN))

If you did it, maybe the file is in other folder and you have to manually move it into ./data/sign/27_2/ folder.

**Comment by HajarAlnamshan** [comment]
> 

thank you so much, after running `python gen_bone_data.py` in data_gen/, immediately the issue was solved.
