### ISSUE TITLE
No such file or directory: 'final_models/val_rgb_final.pth'

### ISSUE THREAD

**Issue by iskenderkahramanoglu** [jackyjsy/CVPR21Chal-SLR#22]
First of all, thanks for the project.

I trained 3DCNN model for RGB frames, using Sign_Isolated_Conv3D_clip.py file.
Now, I will run the Sign_Isolated_Conv3D_clip_finetune.py file.
In 88th row of the file, a pretrained model is loading that named val_rgb.pth.
However, this model does not in final_models directory.
How can i find this model?
Or is this model, output of first stage training?
I've tried use checkpoint/rgb_final/sign_resnet2d+1_epoch100.pth file but got error.

**Comment by jackyjsy** [comment]
Hi there, we didn't provide "val_rgb_final.pth", but you can rename your own model that you obtained from running Sign_Isolated_Conv3D_clip.py to be loaded during finetuning. Please let me know if you still get errors.
