### ISSUE TITLE
AUTSL dataset corrupted or in unknown format

### ISSUE THREAD

**Issue by 98yaoyaoha** [jackyjsy/CVPR21Chal-SLR#24]
Hello thank you so much for your code.

When I downloaded AUSTL datasets from the official website and unpacked it, it showed unknown format or was corrupted.  How should I download and unpack correctly?  By the way, where should I download CSL and WLASL datasets?  

I would appreciate it if you could reply.Thank you very much.

**Comment by jackyjsy** [comment]
Hi there. The link to CSL dataset is [here](http://home.ustc.edu.cn/~pjh/openresources/cslr-dataset-2015/index.html). You will need to request the dataset from the authors. For WLASL dataset [link](https://dxli94.github.io/WLASL/), many YouTube video links no longer exist, but you can request missing videos from the authors (Dongxu Li and Hongdong Li).

For AUTSL dataset, I recommend that you download from their official [website](https://chalearnlap.cvc.uab.cat/dataset/40/description/#). You can verify your downloads before you unpack them to avoid errors.

I have upload my preprocessed skeleton data for SL-GCN for WLASL, AUTSL, and CSL datasets. You can found them via Google Drive link [here](https://drive.google.com/drive/folders/1VUQsh_nf70slT4YsC-UzTCAZ3jB_uFKX?usp=sharing)

Please do not hesitate to let me know if you have any further questions.

**Comment by 98yaoyaoha** [comment]
Hello,Thank you for your reply. I tried to use your preprocessed skeleton data, but I'm sorry that this website can't be opened.  

I would appreciate it if you could reply.Thank you very much.

**Comment by jackyjsy** [comment]
> Hello,Thank you for your reply. I tried to use your preprocessed skeleton data, but I'm sorry that this website can't be opened.
> 
> I would appreciate it if you could reply.Thank you very much.

Can you clarify that which specific website cannot be opened? The Google Drive one?

**Comment by 98yaoyaoha** [comment]
> > Hello,Thank you for your reply. I tried to use your preprocessed skeleton data, but I'm sorry that this website can't be opened.
> > I would appreciate it if you could reply.Thank you very much.
> 
> Can you clarify that which specific website cannot be opened? The Google Drive one?

Hi. I have solved this problem just now, thank you for your patient answer.
