### ISSUE TITLE
Hi ! I'm impressed by your repo. When I try to extract skeleton features. where can I find the file "wholebody_hrnet_w48_384x384.pth" ? Thank you 

### ISSUE THREAD

**Issue by STAROFWIND** [jackyjsy/CVPR21Chal-SLR#3]

**Comment by jackyjsy** [comment]
Thanks! The file can also be found in our google drive of pretrained models (wholepose subfolder): https://drive.google.com/drive/folders/1VcbTfnRa95XYxRB6JPdTiHvIzipqQeW3?usp=sharing

**Comment by STAROFWIND** [comment]
OMG ! I missed it. Thank you so much !!!
