### ISSUE TITLE
Hi. I have already tried to run and test your code. But at the end, how can I know what the sign means ? ( the model only classifies into class from 0 - 225). I also try to find mapping-label file but I can not. Are there any label files like this ? Thank you !!!

### ISSUE THREAD

**Issue by STAROFWIND** [jackyjsy/CVPR21Chal-SLR#8]

**Comment by jackyjsy** [comment]
When we were at the challenge, the AUTSL dataset didn't release the meanings of their class labels. But I just checked that they have released the label meaning recently. Here's the [link](https://data.chalearnlap.cvc.uab.cat/AuTSL/data/SignList_ClassId_TR_EN.csv).

**Comment by STAROFWIND** [comment]
Thank you so much ! this is too indulging to me. So amazing and fantastic repo !!!
