### ISSUE TITLE
How will I use it on my camera for testing

### ISSUE THREAD

**Issue by syhewanglan** [jackyjsy/CVPR21Chal-SLR#9]
I want to apply this great model to the camera for testing, what should I do

**Comment by jackyjsy** [comment]
This repo is developed for challenge results reproducing. There is no easy way to do real-time testing. If you want to test it on camera, you need to record video clips from your camera, then follow the data preprocessing steps to extract features, load the provided pretrained models, and test on them. Note that the pretrained models were trained on the AUTSL dataset, so they work for Turkish sign language inputs only.
